#development version of configurations
server:
  port: 8083

#Database connections

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app_yt
    username: root
    password: SonuSingh@20564

#    hikari:
#      pool-name: HikariCP
#      maximun-pool-size: 5
#      connection-timeout: 10000
#      idle-timeout: 600000
#      max-timeout: 1800000
#      validation-timeout: 1800000
#      leak-detection-thresholf: 0
#      initialization-fail-timeout: -1

# jpa and hibernate configurations
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true